routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/home');
});
Route::get('/', 'HomeController@index');

Route::resource('events', 'EventController');
Route::resource('hotlines', 'HotlineController');
Route::resource('touristspots', 'TouristspotController');
Route::resource('resorts', 'ResortController');
Route::resource('owners', 'OwnerController');

//Route::post('');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Event extends Model
{
    use SoftDeletes;
    protected $table = 'events';
    protected $fillable = [
        'name',
        'detail',
        'location',
        'date',
    ];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::orderBy('id', 'desc')->paginate(10);
        return view('events.index', ['events' => $events]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'      => 'required|min:3',
            'location'  => 'required',
            'date'      => 'required',
            'detail'    => 'required'
        ]);

        Event::create([
            'name'      => $request->name,
            'location'  => $request->location,
            'date'      => $request->date,
            'detail'    => $request->detail,
        ]);

        session()->flash('message', 'Successfully Added!!');

        return redirect(route('events.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('events.show', ['event' => $event]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('events.edit', compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        $event->name        = $request->name;
        $event->location    = $request->location;
        $event->detail      = $request->detail;
        $event->date        = $request->date;
        $event->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('events.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        $event->delete();

        session()->flash('message', 'Successfully Deleted!!');

        return redirect(route('events.index'));
    }
}

resources/views/events/create.blade.php
@extends('layout')

@section('title', 'Add Event')

@section('content')
    <h2 class="my-3">Add Event</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('events.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Event Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Event Name">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="location">Event location</label>
                    <input type="text" class="form-control" id="location" name="location" placeholder="Event location">
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="date">Date</label>
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <input type="text" id="date" name="date" placeholder="M/dd/YYYY H:mm" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="detail">Event Details</label>
            <textarea type="text" class="form-control" id="detail" name="detail" placeholder="Event Details" rows="10"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Submit</button>
        </div>
    </form>
@stop

@section('script')
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
    </script>
@stop

resources/views/events/edit.blade.php
@extends('layout')

@section('title', 'Edit Event')

@section('content')
    <h2 class="my-3">Update Event</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('events.update', $event->id) }}" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Event Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Event Name" value="{{ $event->name }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="location">Event location</label>
                    <input type="text" class="form-control" id="location" name="location" placeholder="Event location" value="{{ $event->location }}">
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="date">Date</label>
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <input type="text" id="date" name="date" placeholder="M/dd/YYYY H:mm" value="{{ $event->date }}" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="detail">Event Details</label>
            <textarea type="text" class="form-control" id="detail" name="detail" placeholder="Event Details" rows="10">
                {{ $event->detail }}
            </textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Submit</button>
        </div>
    </form>
@stop

@section('script')
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
    </script>
@stop

resources/views/events/index.blade.php
@extends('layout')
@section('title', 'Event List')

@section('content')
    <h4>Events</h4>
    <a class="btn btn-sm btn-info my-2" href="{{ route('events.create') }}">Add Event</a>
    <div>
        @if (session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <hr>
        @if (count($events))
            <table class="table table-light table-bordered table-striped">
                <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Event Location</th>
                    <th>Event Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($events as $event)
                    <tr>
                        <td>{{ $event->name }}</td>
                        <td>{{ $event->location }}</td>
                        <td>{{ $event->date }}</td>
                        <td>
                            @csrf
                            <a class="btn btn-sm btn-success" href="{{ route('events.show', $event->id) }}">View</a>
                            <a class="btn btn-sm btn-primary" href="{{ route('events.edit', $event->id) }}">Edit</a>
                            <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete{{ $event->id }}">Delete</button>

                            {{--delete modal--}}
                            <div class="modal" id="delete{{ $event->id }}" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h5 class="modal-title text-center">Delete Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body text-center">
                                            <p>Are you sure you want to delete?</p>

                                            <form class="d-inline-block" method="post" action="{{ route('events.destroy', $event->id) }}">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $events->links() }}
        @else
            <div class="" align="center">
                <h4>No data!</h4>
            </div>
        @endif
    </div>
@stop

resources/views/events/show.blade.php
@extends('layout')

@section('title', 'Event List')

@section('content')
    <h4>Events {{ $event->name }}</h4>
    <a class="btn btn-sm btn-outline-info" href="{{ route('events.edit', $event->id) }}">Edit</a>
    <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#delete">Delete</button>
    <hr>
    <div class="my-2">
        <div class="mb-3">
            <i class="fa fa-pin"></i>
            {{ $event->location }}
        </div>
        <div class="card-title">
            <h5>Details</h5>
        </div>
        <div class="card-body">
            {{ $event->detail }}
        </div>
    </div>

    {{--delete modal--}}
    <div class="modal" id="delete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title text-center">Delete Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <p>Are you sure you want to delete?</p>

                    <form class="d-inline-block" method="post" action="{{ route('events.destroy', $event->id) }}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@stop