routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/home');
});
Route::get('/', 'HomeController@index');

Route::resource('events', 'EventController');
Route::resource('hotlines', 'HotlineController');
Route::resource('touristspots', 'TouristspotController');
Route::resource('resorts', 'ResortController');
Route::resource('owners', 'OwnerController');

//Route::post('');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Resort.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Resort extends Model
{
    use SoftDeletes;
    protected $guarded = [];
}

app/Http/Controllers/ResortController.php
<?php

namespace App\Http\Controllers;

use App\Resort;
use Illuminate\Http\Request;

class ResortController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resorts = Resort::orderBy('updated_at', 'desc')->paginate(10);
        return view('resorts.index', ['resorts' => $resorts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('resorts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'      => 'required|min:3',
            'contact'  => 'required',
            'location'  => 'required',
            'category'  => 'required',
            'description'  => 'required',
            'amenity'  => 'required',
        ]);

        Resort::create([
            'name'      => $request->name,
            'contact'  => $request->contact,
            'location'  => $request->location,
            'category'  => $request->category,
            'description'  => $request->description,
            'amenity'  => $request->amenity,
        ]);

        session()->flash('message', 'Successfully Added!!');

        return redirect(route('resorts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Resort  $resort
     * @return \Illuminate\Http\Response
     */
    public function show(Resort $resort)
    {
        return view('resorts.show', ['resort' => $resort]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Resort  $resort
     * @return \Illuminate\Http\Response
     */
    public function edit(Resort $resort)
    {
        return view('resorts.edit', ['resort' => $resort]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Resort  $resort
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Resort $resort)
    {
        $resort->name           = $request->name;
        $resort->contact        = $request->contact;
        $resort->location       = $request->location;
        $resort->amenity        = $request->amenity;
        $resort->category       = $request->category;
        $resort->description    = $request->description;
        $resort->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('resorts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Resort  $resort
     * @return \Illuminate\Http\Response
     */
    public function destroy(Resort $resort)
    {
        $resort->delete();

        session()->flash('message', 'Successfully Deleted!!');

        return redirect(route('resorts.index'));
    }
}

resources/views/resorts/create.blade.php
@extends('layout')

@section('title', 'Add Resort')

@section('content')
    <h2 class="my-3">Add Resort</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('resorts.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="contact">Contact No.</label>
                    <input type="text" class="form-control" id="contact" name="contact" placeholder="Contact No.">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="location">location</label>
                    <input type="text" class="form-control" id="location" name="location" placeholder="Location">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="category">Category</label>
                    <input type="text" class="form-control" id="category" name="category" placeholder="Category">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="amenity">Amenity</label>
                    <input type="text" class="form-control" id="amenity" name="amenity" placeholder="Amenity">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control" id="description" name="description" placeholder="Description" rows="10"></textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Submit</button>
        </div>
    </form>
@stop

resources/views/resorts/edit.blade.php
@extends('layout')

@section('title', 'Add Resort')

@section('content')
    <h2 class="my-3">Add Resort</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('resorts.update', $resort->id) }}" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ $resort->name }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="contact">Contact No.</label>
                    <input type="text" class="form-control" id="contact" name="contact" placeholder="Contact No." value="{{ $resort->contact }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="location">location</label>
                    <input type="text" class="form-control" id="location" name="location" placeholder="Location" value="{{ $resort->location }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="category">Category</label>
                    <input type="text" class="form-control" id="category" name="category" placeholder="Category" value="{{ $resort->category }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="amenity">Amenity</label>
                    <input type="text" class="form-control" id="amenity" name="amenity" placeholder="Amenity" value="{{ $resort->amenity }}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea class="form-control" id="description" name="description" placeholder="Description" rows="10">
                        {{ $resort->description }}
                    </textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Update</button>
        </div>
    </form>
@stop

resources/views/resorts/index.blade.php
@extends('layout')
@section('title', 'Resort')

@section('content')
    <h4>Resorts</h4>
    <a class="btn btn-sm btn-info my-2" href="{{ route('resorts.create') }}">Add Resort</a>
    <div>
        @if (session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <hr>
        @if (count($resorts))
            <table class="table table-light table-bordered table-striped">
                <thead>
                <tr>
                    <th>Resort Name</th>
                    <th>Contact No.</th>
                    <th>Location</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($resorts as $resort)
                    <tr>
                        <td>{{ $resort->name }}</td>
                        <td>{{ $resort->contact }}</td>
                        <td>{{ $resort->location }}</td>
                        <td>{{ $resort->category }}</td>
                        <td>
                            @csrf
                            <a class="btn btn-sm btn-success" href="{{ route('resorts.show', $resort->id) }}">View</a>
                            <a class="btn btn-sm btn-primary" href="{{ route('resorts.edit', $resort->id) }}">Edit</a>
                            <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete{{ $resort->id }}">Delete</button>
                            {{--delete modal--}}
                            <div class="modal" id="delete{{ $resort->id }}" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h5 class="modal-title text-center">Delete Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body text-center">
                                            <p>Are you sure you want to delete?</p>

                                            <form class="d-inline-block" method="post" action="{{ route('resorts.destroy', $resort->id) }}">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $resorts->links() }}
        @else
            <div class="" align="center">
                <h4>No data!</h4>
            </div>
        @endif
    </div>
@stop

resources/views/resorts/show.blade.php
@extends('layout')

@section('title', 'Tourist Spot List')

@section('content')
    <h4>Resort <small>{{ $resort->name }}</small></h4>
    <a class="btn btn-sm btn-outline-info" href="{{ route('resorts.edit', $resort->id) }}">Edit</a>
    <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#delete">Delete</button>
    <hr>
    <div class="my-2">
        <div class="mb-3">
            {{ $resort->location }} |
            {{ $resort->category }} |
            {{ $resort->contact }}
        </div>
        <div class="card-title">
            <h5>Description</h5>
        </div>
        <div class="card-body">
            {{ $resort->description }}
        </div>
    </div>
    <div class="my-2">
        <div class="card-title">
            <h5>Amenity</h5>
        </div>
        <div class="card-body">
            {{ $resort->amenity }}
        </div>
    </div>

    {{--delete modal--}}
    <div class="modal" id="delete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title text-center">Delete Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <p>Are you sure you want to delete?</p>

                    <form class="d-inline-block" method="post" action="{{ route('resorts.destroy', $resort->id) }}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@stop