routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/home');
});
Route::get('/', 'HomeController@index');

Route::resource('events', 'EventController');
Route::resource('hotlines', 'HotlineController');
Route::resource('touristspots', 'TouristspotController');
Route::resource('resorts', 'ResortController');
Route::resource('owners', 'OwnerController');

//Route::post('');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Hotline.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hotline extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/HotlineController.php
<?php

namespace App\Http\Controllers;

use App\Hotline;
use Illuminate\Http\Request;

class HotlineController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hotlines = Hotline::orderBy('updated_at', 'desc')->paginate(10);
        return view('hotlines.index', ['hotlines' => $hotlines]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hotlines.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'      => 'required|min:3',
            'contact'  => 'required',
        ]);

        Hotline::create([
            'name'      => $request->name,
            'contact'  => $request->contact,
        ]);

        session()->flash('message', 'Successfully Added!!');

        return redirect(route('hotlines.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hotline  $hotline
     * @return \Illuminate\Http\Response
     */
    public function show(Hotline $hotline)
    {
        return view('hotlines.show', ['hotline' => $hotline]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hotline  $hotline
     * @return \Illuminate\Http\Response
     */
    public function edit(Hotline $hotline)
    {
        return view('hotlines.edit', ['hotline' => $hotline]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Hotline  $hotline
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hotline $hotline)
    {
        $hotline->name       = $request->name;
        $hotline->contact    = $request->contact;
        $hotline->save();

        session()->flash('message', 'Successfully Updated!!');

        return redirect(route('hotlines.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Hotline  $hotline
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hotline $hotline)
    {
        $hotline->delete();

        session()->flash('message', 'Successfully Deleted!!');

        return redirect(route('hotlines.index'));
    }
}

resources/views/hotlines/create.blade.php
@extends('layout')

@section('title', 'Add Hotline')

@section('content')
    <h2 class="my-3">Add Hotline</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('hotlines.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Hotline Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Hotline Name">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="contact">Contact</label>
                    <input type="text" class="form-control" id="contact" name="contact" placeholder="Contact">
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Submit</button>
        </div>
    </form>
@stop

resources/views/hotlines/edit.blade.php
@extends('layout')

@section('title', 'Edit Hotline')

@section('content')
    <h2 class="my-3">Update Hotline</h2><hr>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <form action="{{ route('hotlines.update', $hotline->id) }}" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="name">Hotline Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Hotline Name" value="{{ $hotline->name }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="contact">Contact Number</label>
                    <input type="text" class="form-control" id="contact" name="contact" placeholder="Hotline location" value="{{ $hotline->contact }}">
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Update</button>
        </div>
    </form>
@stop

resources/views/hotlines/index.blade.php
@extends('layout')
@section('title', 'Hotline List')

@section('content')
    <h4>Hotlines</h4>
    <a class="btn btn-sm btn-info my-2" href="{{ route('hotlines.create') }}">Add Hotline Contact</a>
    <div>
        @if (session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <hr>
        @if (count($hotlines))
            <table class="table table-light table-bordered table-striped">
                <thead>
                <tr>
                    <th>Hotline Name</th>
                    <th>Hotline Contact</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($hotlines as $hotline)
                    <tr>
                        <td>{{ $hotline->name }}</td>
                        <td>{{ $hotline->contact }}</td>
                        <td>
                            @csrf
                            {{--<a class="btn btn-sm btn-success" href="{{ route('hotlines.show', $hotline->id) }}">View</a>--}}
                            <a class="btn btn-sm btn-primary" href="{{ route('hotlines.edit', $hotline->id) }}">Edit</a>
                            <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete{{ $hotline->id }}">Delete</button>

                            {{--delete modal--}}
                            <div class="modal" id="delete{{ $hotline->id }}" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h5 class="modal-title text-center">Delete Confirmation</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body text-center">
                                            <p>Are you sure you want to delete?</p>

                                            <form class="d-inline-block" method="post" action="{{ route('hotlines.destroy', $hotline->id) }}">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $hotlines->links() }}
        @else
            <div class="" align="center">
                <h4>No data!</h4>
            </div>
        @endif
    </div>
@stop